version: "3"
services:
  nats:
    image: arm32v7/nats:2.9.15
    container_name: runttare-nats
    ports:
      - "4222:4222"
      - "4280:4280"
      - "6222:6222"
      - "8222:8222"
    command: "-c /etc/nats/nats-server.conf"
    volumes:
      - ./conf/nats.conf:/etc/nats/nats-server.conf:ro
    networks:
      - runttare

  worker:
    image: villeristi/runttare-worker:latest
    container_name: runttare-worker
    build:
      context: ./worker
      target: development
      args:
        BASE_IMG: golang:1.21.1-bullseye
    restart: on-failure
    privileged: true
    volumes:
      - ./worker:/app
    environment:
      - RUNTTARE_PIN_PISTON=17
      - RUNTTARE_PIN_STATUS=27
      - RUNTTARE_PIN_ACK=22
      - RUNTTARE_SIMULATE=true
      - RUNTTARE_TIMEOUT=3 # Seconds
      - RUNTTARE_NATS_SERVER=nats://nats:4222
    networks:
      - runttare
    depends_on:
      nats:
        condition: service_started

  # ui:
  #   image: villeristi/runttare-ui:latest
  #   container_name: runttare-ui
  #   build:
  #     context: ./ui
  #     target: development
  #     args:
  #       BROKER_URL: ws://localhost:4280
  #       BASE_IMG: node:18-alpine3.17
  #   restart: on-failure
  #   volumes:
  #     - ./ui:/usr/src/app/
  #     - /usr/src/app/node_modules/
  #   ports:
  #     - 5000:3000
  #   environment:
  #     - REACT_APP_BROKER_URL=ws://localhost:4280
  #   networks:
  #     - runttare
  #   depends_on:
  #     nats:
  #       condition: service_started
  #     worker:
  #       condition: service_started


volumes:
  container-data:

networks:
  runttare:
    name: runttare_network
