version: "3"
services:

  api:
    build:
      context: ./api
      target: production
    container_name: api
    restart: on-failure
    privileged: true
    volumes:
      - ./api:/usr/src/app
      - ./runtta.db:/usr/src/app/dist/runtta.db
      - /usr/src/app/dist/
      - /usr/src/app/node_modules/
    ports:
      - "8000:8000"
    environment:
      - "RUNTTA_TIMEOUT=3000"
      - "RUNTTA_PISTON_PIN=17"
      - "RUNTTA_STATUS_PIN=27"

  ui:
    container_name: ui
    build:
      context: ./ui
      target: production
      args:
        API_URL: http://runttare.local:8000/runtta
        BROKER_URL: ws://runttare.local:8000/ws
    restart: on-failure
    volumes:
      - ./ui:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - "80:80"
    environment:
      - "REACT_APP_API_URL=http://runttare.local:8000/runtta"
      - "REACT_APP_BROKER_URL=ws://runttare.local:8000/ws"
    depends_on:
      - api

volumes:
  container-data:

networks:
  default:
    name: runttare_network
